from flask import Flask, render_template, request

app = Flask(__name__)

qavi_responses = {
   "who is qavi": "Qavi Shaikh is a multi-talented individual with a diverse skill set. They excel as a MERN Stack Developer, working on web applications using MongoDB, Express.js, React.js, and Node.js. Additionally, they are a freelance professional, offering their expertise to clients worldwide. As a teacher, Qavi SHaikh shares their knowledge and passion for IT with others, making a positive impact on the learning journey of many students. Their dedication to the field of IT has earned them numerous awards and certifications, demonstrating their commitment to excellence. Currently, Qavi Shaikh is expanding their horizons by diving into the fascinating world of Artificial Intelligence, while also showcasing their creativity as a graphics designer. Qavi Shaikh is also the founder of Digital Web Creations startup, where they lead a team in creating innovative web solutions for clients.",
   "tell me about": "Qavi Shaikh is a multi-talented individual with a diverse skill set. They excel as a MERN Stack Developer, working on web applications using MongoDB, Express.js, React.js, and Node.js. Additionally, they are a freelance professional, offering their expertise to clients worldwide. As a teacher, Qavi SHaikh shares their knowledge and passion for IT with others, making a positive impact on the learning journey of many students. Their dedication to the field of IT has earned them numerous awards and certifications, demonstrating their commitment to excellence. Currently, Qavi Shaikh is expanding their horizons by diving into the fascinating world of Artificial Intelligence, while also showcasing their creativity as a graphics designer. Qavi Shaikh is also the founder of Digital Web Creations startup, where they lead a team in creating innovative web solutions for clients.",
  "what is qavi background": "Qavi Shaikh has a rich background in the field of IT. They started their journey as a MERN Stack Developer, honing their skills in web development with technologies like MongoDB, Express.js, React.js, and Node.js. As a freelancer, Qavi has gained valuable experience working with clients from various industries, further expanding their expertise. Their passion for sharing knowledge led them to become a teacher, where they have positively impacted the learning journeys of many students.",
  "what is qavi's area of interest": "Qavi Shaikh is particularly research about the field of Artificial Intelligence (AI), with a strong focus on Natural Language Processing (NLP) and Machine Learning. He is fascinated by the potential of AI to understand and generate human language, and they enjoy exploring algorithms and techniques that enable machines to learn from data and make predictions. Qavi Shaikh is actively involved in learning and experimenting with various NLP and Machine Learning models, seeking to apply them to real-world problems and drive innovation in these domains.",
  "what are qavi's expertise": "Qavi Shaikh has a diverse range of expertise in the field of IT. As a skilled MERN Stack Developer, they excel in building robust and scalable web applications using MongoDB, Express.js, React.js, and Node.js. Their experience as a freelancer has honed their ability to adapt to various project requirements and deliver high-quality solutions.",
  "what are qavi's achievements": "Qavi Shaikh has achieved remarkable success and recognition throughout their career in the field of IT. They have received numerous awards for their innovative business ideas, including awards at GC University. Their contributions to education were acknowledged with the prestigious Best Teacher Award in Sindh. Qavi has also been honored for their excellence in web development, winning awards at SMIT. Additionally, they demonstrated their skills and expertise by securing the 2nd position in an inter-university IT competition, showcasing their talent on a broader platform. Qavi has further augmented their knowledge with certifications in Artificial Intelligence from Coursera, digital marketing certifications from DigiSkills, and certificates in graphics designing. These achievements reflect QaviS Sahikh's dedication, expertise, and continuous pursuit of excellence in various domains within the IT industry.",
  "what is qavi's current role": "Currently, Qavi Shaikh is actively engaged in various endeavors. They are undertaking freelance projects in web development, utilizing their expertise to create innovative solutions for clients. Additionally, Qavi Shaikh is sharing their knowledge and skills in web development through teaching, making a meaningful impact on the next generation of IT professionals. Alongside, Qavi Shaikh is immersed in research and learning within the fields of Artificial Intelligence and Machine Learning, exploring new advancements and techniques to broaden their expertise.",
  "what are qavi's goals": "Qavi Shaikh has ambitious goals set for their future in the IT field. They aspire to complete a Ph.D. program abroad, focusing on AI-related research projects to deepen their expertise and contribute to the advancement of the field. Additionally, [Your name] aims to secure a remote job in Germany, leveraging their skills and experience to excel in a global tech environment. They also strive to become a top-rated freelancer on platforms like Fiverr and Upwork, showcasing their expertise and delivering exceptional results to clients worldwide. Furthermore, Qavi Shaikh is passionate about raising awareness of technology among school and college students, aiming to provide them with the necessary knowledge and skills to pursue successful careers in the tech industry.",
  "how can I learn more about qavi's work": "If you want to learn more about Qavi's work, you can check Qavi Shaikh profiles on LinkedIn or any other social media platform. Qavi Shaikh regularly updates his profiles with [his/her] latest projects, achievements, and insights into the IT industry. Additionally, you can connect with Qavi Shaikh directly through email or social media channels to inquire about Qavi's work and expertise. Qavi Shaikh is also active in various tech-related events and communities, where you can engage with Qavi Shaikh and learn more about Qavi's contributions to the field of IT.",
  "what can you tell me about Qavi's personality": "Qavi's personality, He is known for his exceptional qualities. They possess a strong drive and determination to excel in everything they pursue, coupled with a deep passion for the field of IT. Qavi Shaikh is ambitious, constantly seeking new challenges and opportunities for growth. They are also highly motivated and dedicated, always putting in their best effort to achieve their goals",
  "Does Qavi have any favorite tech blogs or podcasts":"Yes, Qavi enjoys reading tech blogs such as TechCrunch and listening to podcasts like Software Engineering Daily to stay informed about the latest developments in the tech industry.",
  "How does Qavi balance work and personal life":"Qavi maintains a balance by prioritizing tasks, setting boundaries, and practicing time management techniques. He also make time for hobbies and relaxation to recharge.",
  "What inspired Qavi to pursue a career in IT":"Qavi's passion for problem-solving and innovation, coupled with a fascination for technology's potential to drive positive change, inspired them to pursue a career in IT.",
  "Has Qavi conducted any workshops or seminars in the past":"Yes, Qavi has conducted workshops and seminars on various topics related to web development, AI, and Machine Learning for students and professionals.",
  "How does Qavi stay updated with the latest trends in technology":"Qavi stays updated by regularly attending tech conferences, participating in online courses and webinars, and engaging with the tech community through forums and social media.",
  "What programming languages does Qavi specialize in":"Qavi specializes in JavaScript for web development, particularly with the MERN (MongoDB, Express.js, React.js, Node.js) stack. and Python,JS",
  "What projects is Qavi currently working on":"Qavi is currently working on various web development projects as a freelancer, along with research in Artificial Intelligence and Machine Learning."
  # Include other responses here
}

def get_response(message):
    if message.lower() in qavi_responses:
        return qavi_responses[message.lower()]
    else:
        return "Sorry, I don't know anything about that. But I can answer questions about Qavi Shaikh!"

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/ask", methods=["POST"])
def ask():
    user_message = request.form["user_message"]
    bot_message = get_response(user_message)
    return {"bot_message": bot_message}

if __name__ == "__main__":
    app.run(debug=True)
